# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:17:11+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    PancrCertificatePostRequest,
    PancrCertificatePostResponse,
    PancrCertificatePostResponse1,
    PancrCertificatePostResponse2,
    PancrCertificatePostResponse3,
    PancrCertificatePostResponse4,
    PancrCertificatePostResponse5,
    PancrCertificatePostResponse6,
    PANVerificationRecordSchema,
)

app = MCPProxy(
    description='Income Tax Department, Govt of India has provided PAN Verification Records to Indian citizens via DigiLocker. You can verify the correctness of your PAN data in real-time using this facility.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Income Tax Department',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/pan/v3'}],
)


@app.post(
    '/pancr/certificate',
    description=""" API to verify PAN Verification Record. """,
    tags=['pan_record_verification'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def pancr(body: PancrCertificatePostRequest = None):
    """
    PAN Verification Record
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
